website/models.py
from . import db
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    firstname = db.Column(db.String(150))
    habits = db.relationship('Habit', backref='user')


class Habit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150))
    notes = db.Column(db.String(10000))
    forever = db.Column(db.Boolean)
    start_date = db.Column(db.DateTime, nullable=True)
    end_date = db.Column(db.DateTime, nullable=True)
    days = db.Column(db.String(50))
    reminder = db.Column(db.Boolean)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    
    completions = db.relationship('HabitCompletion', back_populates='habit', cascade="all, delete-orphan")
    
class HabitCompletion(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    habit_id = db.Column(db.Integer, db.ForeignKey('habit.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    completion_notes = db.Column(db.String(5000))

    habit = db.relationship('Habit', back_populates='completions')

website/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
import os
from .views import home, review_progress

db = SQLAlchemy()
DB_NAME = "database.db"

def create_database(app):
    app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
    db.init_app(app)
    if not os.path.exists(f'website/{DB_NAME}'):
        with app.app_context():
            db.create_all()
            print("Created Database!")        
            
def register_blueprints(app):
    from .auth import auth
    from .habit_routes import habit_control
    
    app.register_blueprint(home, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    app.register_blueprint(habit_control, url_prefix="/")
    app.register_blueprint(review_progress, url_prefix="/review_prog/")

def create_login_manager(app):
    from .models import User
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "sjkdfj283472983;sfd3{D8D8{{SDLKJ4LK4L4K4L4KL4L4KK44L}"

    create_login_manager(app)
    register_blueprints(app)
    create_database(app)
    
    return app

website/auth.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, login_user, logout_user

auth = Blueprint("auth", __name__)


@auth.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        
        if user := User.query.filter_by(email=email).first(): # := is assignment with check
            print('here')
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('home.homepage'))
            else:
                flash("Incorrect password. Try again!", category="error")
        else:
            flash("Email does not exist", category="error")
    return render_template("login.html")

@auth.route('/signup/', methods=['GET', 'POST'])
def sign_up():
    from . import db    
    
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstname')
        password1 = request.form.get('psw')
        password2 = request.form.get('psw-repeat')
        print('here')
        
        if user := User.query.filter_by(email=email).first():
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be greater than 4 characters.", category="error")
        elif len(first_name) < 2:
            flash("First name must be greater than 1 character.", category="error")
        elif password1 != password2:
            flash("Passwords don\'t match.", category="error")
        elif len(password1) < 7:
            flash("Password must be at least 7 characters.", category="error")
        else:
            new_user = User(email=email, firstname=first_name, password=generate_password_hash(password1))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('home.homepage'))
    return render_template("sign_up.html")

@auth.route('/forgot_pwd/')
def forgot_pwd():
    return render_template("forgot_pwd.html")

@auth.route("/logout/")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

home = Blueprint("home", __name__)
review_progress = Blueprint("review_progress", __name__)


@home.route("/")
@login_required
def homepage():
    return render_template("homepage.html", user=current_user)


@review_progress.route("/")
def review_page():
    return render_template("review.html")

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{%block title%}Base{%endblock%}</title>
    <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
        crossorigin="anonymous"
        />
        <link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous"/>
    {% block head %}
    {% endblock %}
</head>
<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
        {%if messages%}
            {%for category, message in messages%}
                {%if category == 'error'%}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {%else%}
                    <div class="alert alert-success alert-dismissable fade show" role="alert">
                        {{message}}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {%endif%}
            {%endfor%}
        {%endif%}
    {% endwith %}
    {% block content %}
    
    {% endblock %}

    <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous">
    </script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous">
    </script>
    <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous">
    </script>
</body>
</html>

website/templates/forgot_pwd.html
{% extends "base.html" %}

{% block title %}Forgot Password{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/forgot_pwd.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Forgot Password</h1>
        <form id="forgot-password-form">
            <div class="form-group">
                <label for="email">Enter your email address:</label>
                <input type="email" id="email" name="email" placeholder="Email Address" required>
            </div>
            <button type="submit">Send Reset Link</button>
        </form>
        <div class="message">
            <p>Remember your password? <a href="{{ url_for('auth.login') }}">Log in here</a></p>
        </div>
    </div>

    <script src="{{ url_for('static', filename='forgot_pwd.js') }}"></script>
{% endblock %}

website/templates/homepage.html
{%extends "base.html"%}

{% block title %}
    Habit Tracker
{% endblock %}

{% block head %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&family=Grey+Qo&family=Luckiest+Guy&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grey+Qo&family=Luckiest+Guy&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Icons From Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Roboto Font -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <!-- Open Sans Font -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="{{url_for('static', filename='styles/homepage.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Grey+Qo&family=Luckiest+Guy&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/habit_popup.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Black+Ops+One&family=Madimi+One&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Underdog&display=swap" rel="stylesheet">
    {% endblock %}


{%block content%}
    <header id="nav">
        <div id="navbar">
            <div id="navbar-left">
                <h1 class="title">Habit Tracker</h1>
                <input type="text" id="search-input" placeholder="  Search" onclick="toggleSearchResults()">
            </div>
            <div id="navbar-center">
            </div>
            <div id="navbar-right">
            </div>
   
    <div class="navbar">
        <img class="navbarPFP" src="{{url_for('static', filename='images/user.png')}}">
        <span class="menu-trigger">{{user.firstname}}</span>
    </div>
    <div class="side-menu" id="sideMenu">
        <div class="profile-section">
            <img src="{{url_for('static', filename='images/user.png')}}" alt="Profile Picture" class="profile-pic">
            <p class="titleForSideMenu">{{user.firstname}}</p>
            <a href="#" class="viewProfile">View profile</a>
            <!-- Test change -->
        </div>
        <ul>
            <li><a href="#">Home</a></li>
            <hr>
            <li><a href="#">Account Settings</a></li>
            <hr>
            <li><a href="{{url_for('review_progress.review_page')}}">Review</a></li>
            <hr>
            <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
            <hr>
        </ul>
    </div>

    <div class="overlay" id="overlay"></div>

    </header>
<div class="full-selection">
    <main>

        <div class="quote-container">
            <p id="quote">QUOTES LOADING....</p>
            </div>


    
            <div id="content">
                <div class="card" style="display: none; position: relative;"> <!-- Set the position to relative here -->
                    <img src="{{url_for('static', filename='images/no_icon.png')}}" class="default-habit-icon" title="Default Habit Icon">
                    <img src="{{url_for('static', filename='images/expand-arrows.png')}}" class="expand-icon" alt="Expand Icon">
                    <img src="{{url_for('static', filename='images/delete.png')}}" class="delete-icon" alt="Delete Icon">
            
                    <h3 class="habit-title">Habit Title</h3>
                    <p class="habit-notes">Habit notes goes here</p>
                    <div class="habit-details hidden">
                        <p class="habit-count-label">Times Completed: <span class="habit-count">0</span></p>
                        <div id="calendar">
                            <div class="week">
                                <div class="day mon">Mon</div>
                                <div class="day tue">Tue</div>
                                <div class="day wed">Wed</div>
                                <div class="day thu">Thu</div>
                                <div class="day fri">Fri</div>
                                <div class="day sat">Sat</div>
                                <div class="day sun">Sun</div>
                            </div>
                        </div>
                        <div class="habit-info">
                            <p>Last completed: <span class="last-completed">N.A</span></p>
                        </div>
                    </div>
                </div>
            </div>
            


    
        <!-- Form Section -->
        <div id="popup-form" style="display: none;">
            <form id="habit-form" class="habit-form">
                <label for="habit-name">Habit Name:</label>
                <input type="text" id="habit-name" name="habit-name" required>

                <label for="notes">Notes</label>
                <textarea id="notes" name="notes"></textarea>
                
                <hr>

                <label>Forever</label>
                <label class="forever-radio-label">
                    <input type="radio" name="forever" value="yes" id="forever-yes" onclick="" required>
                    Yes
                </label>
                <label class="forever-radio-label">
                    <input type="radio" name="forever" value="no" id="forever-no" onclick="" required>
                    No
                </label>
                <div id="dates">
                    <label>Start Date: <input type="date" name="start-date"></label>
                    <label>End Date: <input type="date" name="end-date"></label>
                </div>

                <hr>

                <label for="days">Days</label>
                <label class="days-label"><input type="checkbox" value="mon" name="mon"> Mon</label>
                <label class="days-label"><input type="checkbox" value="tue" name="tue"> Tue</label>
                <label class="days-label"><input type="checkbox" value="wed" name="wed"> Wed</label>
                <label class="days-label"><input type="checkbox" value="thu" name="thu"> Thu</label>
                <label class="days-label"><input type="checkbox" value="fri" name="fri"> Fri</label>
                <label class="days-label"><input type="checkbox" value="sat" name="sat"> Sat</label>
                <label class="days-label"><input type="checkbox" value="sun" name="sun"> Sun</label>

                <hr>

                <label>Reminder</label>
                <label class="reminder-radio-label">
                    <input type="radio" name="reminder" value="yes" id="reminder-yes" required>
                    Yes
                </label>
                <label class="reminder-radio-label">
                    <input type="radio" name="reminder" value="no" id="reminder-no" required>
                    No
                </label>
            </form>
        </div>

        <div class="todo-container">
            <h3>To-Do List</h3>
            <input type="text" id="todo-input" placeholder="Enter a task">
            <button id="add-task">Add</button>
            <ul id="todo-list"></ul>
            <button id="clear-tasks" class="clear-btn">Clear All</button>
        </div>

        <section class="button-section">
            <button id="create-habit-btn" class="button">
                Create New Habit +
            </button>
        </section>    
    </main>
    <script>
        const trashIconUrl = `<img style="width: 40px; height: 40px;" src="{{url_for('static', filename='images/trash.png')}}" alt="trash_icon">`;
    </script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script type="module" src="{{url_for('static', filename='habit.js')}}"></script>
    <script type="module" src="{{url_for('static', filename='utils.js')}}"></script>
    <script type="module" src="{{url_for('static', filename='homepage.js')}}"></script>
    <script type="module" src="{{url_for('static', filename='habit_popup.js')}}"></script>

</div>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{%endblock%}

website/templates/login.html
{% extends "base.html" %}

{% block title %}Login Page{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/login.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Calistoga&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  <div class="login-box">
    <h2>Welcome Back!</h2>
    <form action="{{ url_for('auth.login') }}" method="post">
      <input class="input-field" type="text" name="email" placeholder="Email" required>
      <input class="input-field" type="password" name="password" placeholder="Password" required>
      <button type="submit" class="login-btn">Login</button>
    </form>
    <div class="bottom-links">
      <p>Don't have an account?&nbsp;&nbsp;<a href="{{ url_for('auth.sign_up') }}" class="link">Sign up</a></p>
      <span class="divider">|</span>
      <a href="{{ url_for('auth.forgot_pwd') }}" class="link">Forgot password?</a>
    </div>
  </div>
</div>
{% endblock %}

website/templates/newpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habit Tracker - Full Review</title>
    <link rel="stylesheet" href="../static/styles/newpage.css">
</head>
<body>
    <div class="main-container">
        <header>
            <h1>Habit Tracker</h1>
            <nav>
                <button id="check-in-tab" class="tab active">Daily Check-in</button>
                <button id="daily-tab" class="tab"></button>
                <button id="weekly-tab" class="tab">Weekly Review</button>
            </nav>
        </header>
        
        <section id="check-in-section" class="content-section active">
            <h2>Daily Check-in</h2>
            <div class="check-in-container">
                <section id="pending-habits">
                    <h3>Pending Habits for the Day</h3>
                    <ul class="habit-list" id="pending-list">
                        <li>
                            <label>
                                <!-- <img src="../static/images/no_icon.png" class="habitTrackerImage" title="no icon"> -->
                                <input type="checkbox" class="habit-checkbox">
                                <span class="habit-name">Drink 8 glasses of water</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <!-- <img src="../static/images/no_icon.png" class="habitTrackerImage" title="no icon"> -->
                                <input type="checkbox" class="habit-checkbox">
                                <span class="habit-name">Read for 30 minutes</span>
                            </label>
                        </li>
                        <!-- Add more habits as needed -->
                    </ul>
                </section>

                <section id="completed-habits" class="hidden">
                    <h3>Completed Habits for the Day</h3>
                    <ul class="habit-list" id="completed-list">
                        <!-- Completed habits will be moved here -->
                    </ul>
                </section>

                <section id="daily-notes">
                    <h3>Notes for the Day (optional)</h3>
                    <textarea id="notes-input" placeholder="Write your notes here..."></textarea>
                </section>
            </div>
        </section>

        <section id="daily-review-section" class="content-section">
            <h2>Daily Review</h2>
            <div class="review-container">
                <div class="habit-summary">
                    <p>Habits completed: <span id="daily-completed">0</span>/5</p>
                    <p>Notes: <textarea id="daily-notes-review"></textarea></p>
                </div>
            </div>
        </section>

        <section id="weekly-review-section" class="content-section">
            <h2>Weekly Review</h2>
            <div class="review-container">
                <div class="habit-summary">
                    <p>Habits completed: <span id="weekly-completed">0</span>/35</p>
                    <p>Overall Rating: 
                        <select id="weekly-rating">
                            <option value="1">1 - Poor</option>
                            <option value="2">2 - Fair</option>
                            <option value="3">3 - Good</option>
                            <option value="4">4 - Very Good</option>
                            <option value="5">5 - Excellent</option>
                        </select>
                    </p>
                    <p>Notes: <textarea id="weekly-notes-review"></textarea></p>
                </div>
            </div>
        </section>
    </div>

    <script src="../static/newpage.js"></script>
</body>
</html>

website/templates/review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habit Tracker - Full Review</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles/review.css')}}">
</head>
<body>
    <div class="main-container">
        <header>
            <h1>Habit Tracker</h1>
            <nav>
                <button id="check-in-tab" class="tab active">Daily Check-in</button>
                <button id="daily-tab" class="tab"></button>
                <button id="weekly-tab" class="tab">Weekly Review</button>
            </nav>
        </header>
        
        <section id="check-in-section" class="content-section active">
            <h2>Daily Check-in</h2>
            <div class="check-in-container">
                <section id="pending-habits">
                    <h3>Pending Habits for the Day</h3>
                    <ul class="habit-list" id="pending-list">
                        <!-- Add more habits as needed -->
                    </ul>
                </section>

                <section id="completed-habits" class="hidden">
                    <h3>Completed Habits for the Day</h3>
                    <ul class="habit-list" id="completed-list">
                        <!-- Completed habits will be moved here -->
                    </ul>
                </section>

                <section id="daily-notes">
                    <h3>Journal for the Day (optional)</h3>
                    <textarea id="notes-input" placeholder="Write your notes here..."></textarea>
                </section>
            </div>
        </section>

        <section id="daily-review-section" class="content-section">
            <h2>Daily Review</h2>
            <div class="review-container">
                <div class="habit-summary">
                    <p>Habits completed: <span id="daily-completed">0</span>/5</p>
                    <p>Notes: <textarea id="daily-notes-review"></textarea></p>
                </div>
            </div>
        </section>

        <section id="weekly-review-section" class="content-section">
            <h2>Weekly Review</h2>
            <div class="review-container">
                <div class="habit-summary">
                    <p>Habits completed: <span id="weekly-completed">0</span>/35</p>
                    <p>Overall Rating: 
                        <select id="weekly-rating">
                            <option value="1">1 - Poor</option>
                            <option value="2">2 - Fair</option>
                            <option value="3">3 - Good</option>
                            <option value="4">4 - Very Good</option>
                            <option value="5">5 - Excellent</option>
                        </select>
                    </p>
                    <p>Notes: <textarea id="weekly-notes-review"></textarea></p>
                </div>
            </div>
        </section>
    </div>

    <script type="module" src="{{url_for('static', filename='daily_review.js')}}"></script>
    <script type="module" src="{{url_for('static', filename='review.js')}}"></script>
</body>
</html>

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/sign_up.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Register</h1>
        <p>Please fill in this form to create an account.</p>
        <hr>

        <form action="{{ url_for('auth.sign_up') }}" method="post">
            <label for="firstname"><b>First Name</b></label>
            <input type="text" placeholder="Enter First Name" name="firstname" id="firstname" required>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" id="email" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" id="psw" required>

            <label for="psw-repeat"><b>Repeat Password</b></label>
            <input type="password" placeholder="Repeat Password" name="psw-repeat" id="psw-repeat" required>
            <hr>
            
            <p>By creating an account you agree to our <a href="#">Terms & Conditions</a>.</p>
            <button type="submit" class="registerbtn">Register</button>
        </form>
        <p style="margin-bottom: -5px;">Already have an account? <a href="{{ url_for('auth.login') }}">Log in</a></p>
    </div>
{% endblock %}